name: coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install LCOV
        run: |
          sudo apt-get update && sudo apt-get install --assume-yes lcov

      - name: Install submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Generate coverage report
        run: |
          node ./lcov-parse.mock.js
          ls coverage

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main

      - name: Deploy Coverage HTML
        uses: Wandalen/wretry.action@master
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          attempt_limit: 3
          attempt_delay: 2000
          command: |
            ls coverage
            git checkout gh-pages
            git add coverage
            git commit -m 'Upload coverage html [skip ci]'
            git push