name: gpt_review

on:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  gpt_review:
    name: GPT review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Actions ChatGPT PR Reviewer
        uses: osl-incubator/github-actions-chatgpt-pr-reviewer@1.0.3
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}  # required
          openai_temperature: 0.5  # optional
          openai_max_tokens: 2048  # optional
          openai_extra_criteria: |  # optional, use `;` for separate the criteria items
            - prefer readable variable name instead of short names like `k` and `v`, when apply;
            - verify `SOLID` principles design pattern violations, when apply;
          github_token: ${{ secrets.GITHUB_TOKEN }}  # required
          github_pr_id: ${{ github.event.number }}  # required